"""Initial schema

Revision ID: 71d4f80c79b6
Revises: 
Create Date: 2026-07-16 05:33:17.790273
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d4f80c79b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration — forward."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=False),
    sa.Column('bay', sa.String(length=10), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', name='seat_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor', 'zone', 'bay', 'seat_number', name='uq_seat_location')
    )
    op.create_index('idx_seat_floor_zone', 'seats', ['floor', 'zone'], unique=False)
    op.create_index('idx_seat_status', 'seats', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='employee_status'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index('idx_employee_name', 'employees', ['name'], unique=False)
    op.create_index('idx_employee_project', 'employees', ['project_id'], unique=False)
    op.create_index('idx_employee_status', 'employees', ['status'], unique=False)
    op.create_table('seat_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_status', sa.Enum('ACTIVE', 'RELEASED', name='allocation_status'), nullable=False),
    sa.Column('allocation_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('released_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alloc_active_employee', 'seat_allocations', ['employee_id'], unique=False)
    op.create_index('idx_alloc_active_seat', 'seat_allocations', ['seat_id'], unique=False)
    op.create_index('idx_alloc_employee', 'seat_allocations', ['employee_id'], unique=False)
    op.create_index('idx_alloc_project', 'seat_allocations', ['project_id'], unique=False)
    op.create_index('idx_alloc_seat', 'seat_allocations', ['seat_id'], unique=False)
    op.create_index('idx_alloc_status', 'seat_allocations', ['allocation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration — backward."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alloc_status', table_name='seat_allocations')
    op.drop_index('idx_alloc_seat', table_name='seat_allocations')
    op.drop_index('idx_alloc_project', table_name='seat_allocations')
    op.drop_index('idx_alloc_employee', table_name='seat_allocations')
    op.drop_index('idx_alloc_active_seat', table_name='seat_allocations')
    op.drop_index('idx_alloc_active_employee', table_name='seat_allocations')
    op.drop_table('seat_allocations')
    op.drop_index('idx_employee_status', table_name='employees')
    op.drop_index('idx_employee_project', table_name='employees')
    op.drop_index('idx_employee_name', table_name='employees')
    op.drop_table('employees')
    op.drop_index('idx_seat_status', table_name='seats')
    op.drop_index('idx_seat_floor_zone', table_name='seats')
    op.drop_table('seats')
    op.drop_table('projects')
    # ### end Alembic commands ###
